In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
manual = pd.read_csv("manual_clean.csv")
manual

    Class                                      File  Alt
0       i  abab984c-ce5d-11eb-b317-38f9d35ea60f.png  NaN
1       i  abba3e7e-ce5d-11eb-b317-38f9d35ea60f.png  NaN
2       i  abe3a16a-ce5d-11eb-b317-38f9d35ea60f.png  NaN
3       i  abf15a58-ce5d-11eb-b317-38f9d35ea60f.png   ii
4       i  ac4b5256-ce5d-11eb-b317-38f9d35ea60f.png   ii
..    ...                                       ...  ...
123     x  b0062b82-ce5d-11eb-b317-38f9d35ea60f.png  NaN
124     x  b0156f52-ce5d-11eb-b317-38f9d35ea60f.png  NaN
125     x  b0235b76-ce5d-11eb-b317-38f9d35ea60f.png  NaN
126     x  b02931ea-ce5d-11eb-b317-38f9d35ea60f.png  NaN
127     x  b0059456-ce5d-11eb-b317-38f9d35ea60f.png  NaN

[128 rows x 3 columns]

In [3]:
for i, row in manual.iterrows():
    if not pd.isnull(row['Alt']):
        try:
            os.replace(f"data/train/{row['Class']}/{row['File']}", f"data/train/{row['Alt']}/{row['File']}")
        except:
            continue
    else:
        try:
            os.remove(f"data/train/{row['Class']}/{row['File']}")
        except:
            continue